### ISSUE TITLE
How do we monitor our acquisition database?

### ISSUE THREAD

**Issue by cmarshak** [aria-jpl/scihub_acquisition_scraper#14]
In addition to previous [issue ticket](https://github.com/aria-jpl/scihub_acquisition_scraper/issues/13#issue-915661491), how do we ensure that all of our SLC acq metadata ES database is up-to-date?

Here are some rough examples - maybe the facets are wrong, but it seems like we can have significantly less acquisition documents in our database for certain time periods.

(Aria)
https://mamba-grq.aria.hysds.io/search/?base64=eyJxdWVyeSI6eyJib29sIjp7Im11c3QiOlt7InRlcm0iOnsiZGF0YXNldC5yYXciOiJhY3F1aXNpdGlvbi1TMS1JV19TTEMifX0seyJxdWVyeV9zdHJpbmciOnsicXVlcnkiOiJtZXRhZGF0YS5zZW5zaW5nU3RhcnQ6ezIwMjAtMDEtMDFUMDA6MDA6MDBaIFRPIDIwMjAtMDEtMDNUMDA6MDA6MDB9IiwiZGVmYXVsdF9vcGVyYXRvciI6Ik9SIn19XX19LCJzb3J0IjpbeyJfdGltZXN0YW1wIjp7Im9yZGVyIjoiZGVzYyJ9fV0sImZpZWxkcyI6WyJfdGltZXN0YW1wIiwiX3NvdXJjZSJdfQ== ( about 1900)

(ASF)
https://search.asf.alaska.edu/#/?start=2020-01-01T00:00:00Z&end=2020-01-02T23:59:59Z&resultsLoaded=true&granule=S1B_IW_SLC__1SDV_20200102T235532_20200102T235602_019645_025205_8E4D-SLC&productTypes=SLC,METADATA_SLC (about 2k)

The change here seems more dramatic:

(aria)
https://mamba-grq.aria.hysds.io/search/?base64=eyJxdWVyeSI6eyJib29sIjp7Im11c3QiOlt7InRlcm0iOnsiZGF0YXNldC5yYXciOiJhY3F1aXNpdGlvbi1TMS1JV19TTEMifX0seyJxdWVyeV9zdHJpbmciOnsicXVlcnkiOiJtZXRhZGF0YS5zZW5zaW5nU3RhcnQ6ezIwMjAtMDUtMjlUMDA6MDA6MDBaIFRPIDIwMjAtMDYtMDFUMDA6MDA6MDB9IiwiZGVmYXVsdF9vcGVyYXRvciI6Ik9SIn19XX19LCJzb3J0IjpbeyJfdGltZXN0YW1wIjp7Im9yZGVyIjoiZGVzYyJ9fV0sImZpZWxkcyI6WyJfdGltZXN0YW1wIiwiX3NvdXJjZSJdfQ== (<250)

(asf)
https://search.asf.alaska.edu/#/?end=2020-05-30T23:59:59Z&resultsLoaded=true&granule=S1A_WV_SLC__1SSV_20200530T234444_20200531T000010_032801_03CCA7_D8B3-METADATA_SLC&productTypes=METADATA_SLC&start=2020-05-29T00:00:00Z (about 2k)

**Comment by marjo-luc** [comment]
This script is likely a good start. It looks for missing slc's, but could be tweaked to compare acquisitions on ESA/ASF against what we have locally.

https://github.com/aria-jpl/ops_scripts2/blob/master/check_acquisitions/check_acquisition_completeness.py

In the past, we relied on the 'best-effort' of our scrapers, and I'd ping ESA/ASF directly to compare acquisition numbers to what we had ingested, every so often, but since there was rarely any discrepancy, I never prioritized the development of an independent checker.

**Comment by cmarshak** [comment]
Ok, this is definitely a start. What are your thoughts creating an AOI that spans the globe and then loop through tracks? Is this feasible in time?

There is no documentation for this repo. How was this meant to be run?

**Comment by marjo-luc** [comment]
Why create a global AOI? You could just set this up as a cron to run however often you'd like and have it iterate through all aoi-track datasets.

I'm not familiar with the code, but reading it, you'll find this snippet that tells you what inputs it takes:
https://github.com/aria-jpl/ops_scripts2/blob/f6a067ee6308641a4fb0ae1269399dd77cccee30/check_acquisitions/check_acquisition_completeness.py#L262

**Comment by cmarshak** [comment]
So for the standard product, this could be run for each AOI and track and things could, in theory, be tracked accordingly after learning about said script/PGE.

For coseismic,  when we have to let the pipeline producing AOITracks in along tracks (that could be previously unmonitored), how would we monitor the SLC metadata in this setting to ensure the enumerator works as expected which relies on this? @riverma 

Maybe I am missing something? 

I know it is recommended to run scrapers over an AOI and track before running the standard product pipeline. Maybe this needs to be done for coseismic?

**Comment by marjo-luc** [comment]
It's only recommended that we run the scrapers over the the AOI's because we do not have a reliable, independent way of confirming our collection of SLC metadata is up-to-date. Ideally, we should be up-to-date with SLC metadata world-wide, so I think it would be best to not think in terms of AOI's or AOI tracks and instead focus on developing an independent checker that works in conjunction with the cron scrapers.

**Comment by riverma** [comment]
@marjo-luc - please go ahead and create a new dev ticket to track the proposed solution you're recommending.
